// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD_V1z2W9l4phpqezu7r8fh_JyeyIQvp9M',
    appId: '1:697108047527:web:34455420728312e78fdd82',
    messagingSenderId: '697108047527',
    projectId: 'task-manager-7b286',
    authDomain: 'task-manager-7b286.firebaseapp.com',
    storageBucket: 'task-manager-7b286.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAW1Fd3gceKM7KUbrX_r5wOgv5gtRmfMGg',
    appId: '1:697108047527:android:8022a449961325688fdd82',
    messagingSenderId: '697108047527',
    projectId: 'task-manager-7b286',
    storageBucket: 'task-manager-7b286.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCdCv4EchvMn5ufNq5UfemllL8cvV4ztWM',
    appId: '1:697108047527:ios:8acf6e73e074b3f48fdd82',
    messagingSenderId: '697108047527',
    projectId: 'task-manager-7b286',
    storageBucket: 'task-manager-7b286.appspot.com',
    iosBundleId: 'com.example.todoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCdCv4EchvMn5ufNq5UfemllL8cvV4ztWM',
    appId: '1:697108047527:ios:c1cdb5ee9da1f1fb8fdd82',
    messagingSenderId: '697108047527',
    projectId: 'task-manager-7b286',
    storageBucket: 'task-manager-7b286.appspot.com',
    iosBundleId: 'com.example.todoApp.RunnerTests',
  );
}
